import { Inter, Advent_Pro } from "next/font/google";
import "../styles/globals.css";

const interSans = Inter({
  subsets: ["latin"],
  variable: "--font-inter-sans",
  display: "swap",
});

const adventPro = Advent_Pro({
  subsets: ["latin"],
  variable: "--font-advent-pro",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${interSans.variable} ${adventPro.variable}`}>
        {children}
      </body>
    </html>
  );
}
